### PR TITLE
patch plugin to go v1.21

### PR DESCRIPTION
**Pull request by troyxmccall**
hi! first of all i love parallels and this plugin - I use it on older 5.1 MacPros for swarm 

and I was hoping to bump this plugin back to being maintained for homebrew, so I figured I'd address some items: 

- update go to v1.21
- fix build flag for Makefile
- alias docker-machine to maintained gitlab version: https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/tags/v0.16.2-gitlab.23

as for the boot2docker iso in your tests: I have my own fork with a modern run-time, but I wasn't sure if you wanted to include that:

https://github.com/troyxmccall/boot2docker

```
Tiny Core Linux: 13.x
Docker: 24.0.7
Linux Kernel: 6.1.x
```

happy to work within whatever params you need

thanks!

### CODE REVIEW

**Comment by afbjorklund** [comment]
The gitlab fork is not maintained for "outside" use:

https://gitlab.com/gitlab-org/ci-cd/docker-machine

**Comment by troyxmccall** [comment]
@afbjorklund that's true, but even homebrew uses the gitlab fork for the docker-machine forumla

https://github.com/Homebrew/homebrew-core/blob/acd64ccfb648e683d69d6ee77804d2add0db69cd/Formula/d/docker-machine.rb

**Comment by afbjorklund** [comment]
They also recently declared an EOL in 2024, so might need something else to continue with machine...

> We will maintain the fork and provide support through the end of the calendar year 2024.

The "[machine-drivers](https://github.com/machine-drivers/machine)" organization was mostly for 3rd party drivers, but not for evolving the main library.

Of course minikube still uses "[minikube-machine](https://github.com/minikube-machine/machine)", but has forked most of the provisioners and whatnot.

----

I didn't actually compare the branches, so I don't know what they added... Rancher also has a fork.

While I _also_ have my own forks of machine and boot2docker, I have mostly switched over to use Lima.

**Comment by troyxmccall** [comment]
@afbjorklund copy that, I'm fine with using my own fork and building my preferred binary myself 

closing as this looks to be something that doesn't need to be generally supported

**Comment by afbjorklund** [comment]
I do like what docker-machine provided, but think it needs something new for 2025?

For podman-machine that evolved into "something else", when Red Hat [took over](https://github.com/boot2podman/machine#deprecated).

**Comment by afbjorklund** [comment]
@troyxmccall : added a reminder for minikube-machine, to cherry-pick any fixes from gitlab-machine...

It also grew some fixes, needed for arm64: https://github.com/minikube-machine/machine-driver-parallels

Note: this is for use as a minikube driver (k8s), which currently all building/embedding all drivers from source

It is not intended for docker-machine / swarm, even if they still share the same old API (i.e. Docker v0.16.2)

**Pull request closed without merging**
