### PR TITLE
Create a bigger initial disk on Parallels Desktop 13.0

### LINKED ISSUE #67: Parallels 13.0 issue
VM never starts.

```
> docker-machine -D create --driver=parallels prl-dev
Docker Machine Version:  0.12.2, build 9371605
Found binary path at /usr/local/bin/docker-machine-driver-parallels
Launching plugin server for driver parallels
Plugin server listening at address 127.0.0.1:58803
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine-driver-parallels
Launching plugin server for driver parallels
Plugin server listening at address 127.0.0.1:58807
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(prl-dev) Calling .GetMachineName
(prl-dev) Calling .DriverName
(prl-dev) Calling .GetCreateFlags
(prl-dev) Calling .SetConfigFromFlags
Running pre-create checks...
(prl-dev) Calling .PreCreateCheck
(prl-dev) DBG | executing: /usr/local/bin/prlctl --version
(prl-dev) DBG | executing: /usr/local/bin/prlsrvctl info --license
(prl-dev) DBG | Found Parallels Desktop version: 13, edition: business
(prl-dev) DBG | executing: /usr/local/bin/prlsrvctl net info Shared
(prl-dev) DBG | local Boot2Docker ISO version:  v17.06.1-ce
(prl-dev) Calling .GetConfigRaw
Creating machine...
(prl-dev) Calling .Create
(prl-dev) DBG | local Boot2Docker ISO version:  v17.06.1-ce
(prl-dev) Copying /Users/rolsen/.docker/machine/cache/boot2docker.iso to /Users/rolsen/.docker/machine/machines/prl-dev/boot2docker.iso...
(prl-dev) Creating SSH key...
(prl-dev) DBG | SSH key: /Users/rolsen/.docker/machine/machines/prl-dev/id_rsa
(prl-dev) Creating Parallels Desktop VM...
(prl-dev) DBG | executing: /usr/local/bin/prlctl --version
(prl-dev) DBG | executing: /usr/local/bin/prlctl create prl-dev --distribution boot2docker --dst /Users/rolsen/.docker/machine/machines/prl-dev --no-hdd
(prl-dev) DBG | executing: /usr/local/bin/prlctl set prl-dev --select-boot-device off --cpus 4 --memsize 4096 --cpu-hotplug off --on-window-close keep-running --longer-battery-life on --3d-accelerate off --device-bootorder cdrom0
(prl-dev) DBG | executing: /usr/local/bin/prlctl set prl-dev --device-set cdrom0 --iface sata --position 0 --image /Users/rolsen/.docker/machine/machines/prl-dev/boot2docker.iso --connect
(prl-dev) DBG | executing: /usr/local/bin/prlctl set prl-dev --device-add hdd --iface sata --position 1 --image /Users/rolsen/.docker/machine/machines/prl-dev/disk.hdd --type plain --size 32
(prl-dev) DBG | Writing magic tar header
(prl-dev) DBG | Writing SSH key tar header
(prl-dev) DBG | HDS image path: /Users/rolsen/.docker/machine/machines/prl-dev/disk.hdd/disk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds
(prl-dev) DBG | executing: /usr/local/bin/prl_disk_tool convert --expanding --hdd /Users/rolsen/.docker/machine/machines/prl-dev/disk.hdd
Error creating machine: Error in driver during machine creation: exit status 2
notifying bugsnag: [Error creating machine: Error in driver during machine creation: exit status 2]
```

```
> /usr/local/bin/prl_disk_tool convert --expanding --hdd /Users/rolsen/.docker/machine/machines/prl-dev/disk.hdd
Unable to open the disk image.
```

```
> ls -la /Users/rolsen/.docker/machine/machines/prl-dev/disk.hdd
total 8
drwxr-xr-x 5 rolsen staff  170 Aug 29 11:12 .
drwx------ 8 rolsen staff  272 Aug 29 11:12 ..
-rw-r--r-- 1 rolsen staff 1600 Aug 29 11:12 DiskDescriptor.xml
-rw-r--r-- 1 rolsen staff 1600 Aug 29 11:12 DiskDescriptor.xml.Backup
-rw-rw-rw- 1 rolsen staff    0 Aug 29 11:12 disk.hdd
```

### PR DESCRIPTION
**Pull request by legal90**
Fixes #67 

That is a workaround for "plain" -> "expanding" disk conversion on Parallels Desktop 13.0.* .
To get it working as before, we need to create a bigger disk image. The minimal size is 1891Mb.
It makes sense only in the creation phase - after that, the disk will be resized to `d.DiskSize`.

### CODE REVIEW

**Comment by romankulikov** [comment]
@legal90, do you really think that it is worth implementing such a check? May be just to declare that a specific interval of Parallels Desktop versions is broken? I'm in doubts frankly.

**Comment by legal90** [comment]
@romankulikov Yes, I just want to release this workaround now, so users will be able to continue using the plugin today, before the "fixed" fersion of Parallels Desktop is released.

Bringing the `go-version` library might look like an overkill, but I think it's not the last time when we need such version constraints for PD features or workarounds.

**Comment by romankulikov** [comment]
Ok.

**Comment by romankulikov** [comment]
Ok.

**Pull request merged**
