### PR TITLE
Make --parallels-memory flag match --driver-memory-size flags

### PR DESCRIPTION
**Pull request by jgeiger**
- The default drivers use --driver-memory-size to set the default
  memory. This also matches the ENV variable name as well.

### CODE REVIEW

**Comment by legal90** [comment]
> The default drivers use --driver-memory-size to set the default memory.

Not quite. `virtualbox`, `hyperv` and `softlayer` drivers use `--<driver>-memory` flag too, without "-size" prefix. There are no any conventions in Docker Machine about these driver options, so each driver could implement their own flags.

@jgeiger Thank you for contribution. I agree that `--parallels-memory-size` would be better, but we can't just rename it because it will break the backward compatibility.
It is better to keep both variants and remove the old one completely only in the next major release.

**Comment by jgeiger** [comment]
I added the -memory-size as a new flag, and check to see if it's defaultMemory. If not, we use it, if so it drops into using the old flag.

I've also submitted a pull request to docker-machine to standardize on using --driver-memory-size for the above mentioned drivers.

**Comment by legal90** [comment]
Thanks! Let's track the discussion in your PR https://github.com/docker/machine/pull/2691.
We'll follow the final decision which Docker Machine maintainers will make.

**Comment by legal90** [comment]
@jgeiger I appreciate the effort you've put to this PR, but we can see that the final decision about CLI design on the Docker Machine side has been delayed.

About our case here - I think it's better just to keep the things simple and continue support the only one expected name of memory flag - `--parallels-memory`. 
Thank you again!

**Pull request closed without merging**
